### ISSUE TITLE
Plugin not being installed any more (CC 2019)

### ISSUE THREAD

**Issue by martijnthe** [adobe-extension-tools/cep-packager#1]
Hi Koen,

First off, thanks for your framework. It's been very useful to get started with CEP using TypeScript.

Unfortunately, "something happened" recently and now a .pkg is no longer correctly installing the plugin. It used to work before. I suspect it has to do with an update of either Adobe CC or updating macOS to Mojave (or both?).

I checked the `.pkg` file and it contains the correct `bundle.zxp`, so that's not the problem.

I suspect the problem is in the [postinstallcs] script. The produced log file contains:
```
cat ~/.installer-debug-log.txt
Running installer...
Installing extension with file path = ./bundle.zxp
Failed to install, status = -403!
Done.
```

None of the paths in that script actually exist, however a folder called `/Library/Application Support/Adobe/CEP/extensions/` does exist:

![screenshot](https://user-images.githubusercontent.com/193881/51246090-cd793f00-1989-11e9-9efe-d20ab23fe98e.png)

What's also a bug is that the installer app is actually stating the installation was successful. I guess this is because the error is being swallowed in [postinstallcs] and is returning status 0.

Edit: I'm using `cep-packager@0.0.21`. But looking at the commit log, I don't think anything has in [postinstallcs] to update to the new `/CEP/extensions` path.

[postinstallcs]: https://github.com/adobe-extension-tools/cep-packager/blob/master/src/templates/macos/postinstallcs.ts

**Comment by vespakoen** [comment]
Hi! thanks for reporting this problem,
The postinstall script runs ExManCmd, and that is where the error is coming from, here is the list of error codes from ExManCmd: https://helpx.adobe.com/exchange/kb/error-codes.html

You seem to be getting:

```
The Add-on installation failed because it is incompatible with installed Adobe applications.

Compatible CC app not found.

Solution: Install the compatible CC application before installing the extensions. Once the application is installed, try installing the extension again. Go to My Exchange, find the extension, and if it is installed, click Uninstall. Wait two minutes for the removal to complete, then click Install.
```

This is coming from what compatible versions you are using in your `CSXS/manifest.xml` file, which is not managed through `cep-packager` (but IS managed through `cep-bundler` in case you are using that!)

https://github.com/adobe-extension-tools/cep-bundler/blob/master/src/templates/manifest.ts#L9
(the from / to is what is important here, if you want to target all versions, try setting `from` to 0 and `to` to 99.9

I will look into better error handling in the installer, it should have reported as failed indeed!

**Comment by martijnthe** [comment]
Thanks for your reply :)

The manifests contains the default list from your template project (we're using the CEP plugin internally, so I haven't bothered changing the list):
```
...
      <Host Name="PHXS" Version="[1.0,99.9]" />
      <Host Name="PHSP" Version="[1.0,99.9]" />
      <Host Name="IDSN" Version="[1.0,99.9]" />
      <Host Name="AICY" Version="[1.0,99.9]" />
      <Host Name="ILST" Version="[1.0,99.9]" />
      <Host Name="PPRO" Version="[1.0,99.9]" />
      <Host Name="PRLD" Version="[1.0,99.9]" />
      <Host Name="AEFT" Version="[1.0,99.9]" />
      <Host Name="FLPR" Version="[1.0,99.9]" />
      <Host Name="AUDT" Version="[1.0,99.9]" />
      <Host Name="DRWV" Version="[1.0,99.9]" />
      <Host Name="MUSE" Version="[1.0,99.9]" />
      <Host Name="KBRG" Version="[1.0,99.9]" />
...
```

I've downloaded ExManCmd from the Adobe site [here] and tried to run it hopefully get more info:
```
$ ./ExManCmd --list all
0 extension installed for Others
 Status                        Extension Name                         Version
=========  =======================================================  ==========
```

Also tried running the other utils:
```
$ ./ExManBridgeTalkCmd
<products>
<product specifier='illustrator-23.064' path='/Applications/Adobe Illustrator CC 2019/Adobe Illustrator.app' locale='en_US'/>
<product specifier='photoshop-130.064' path='/Applications/Adobe Photoshop CC 2019/Adobe Photoshop CC 2019.app' locale='en_US'/>
</products>
```

Both Illustrator and Photoshop are installed as you can see. So in theory it should match the apps that are declared in the manifest.xml...

I also noticed some logs in the Installer.app itself (pressing `cmd+l` shows the logs):
```
...
Jan 16 11:52:05 mac install_monitor[51496]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Jan 16 11:52:05 mac installd[415]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.zKSOLn/Scripts/co.misusu.ai18n.Yi45Uv
Jan 16 11:52:06 mac installd[415]: ./postinstall: Removing co.misusu.ai18n
Jan 16 11:52:06 mac installd[415]: ./postinstall: Failed to remove co.misusu.ai18n, status = -451
Jan 16 11:52:17 mac installd[415]: ./postinstall: usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
Jan 16 11:52:17 mac installd[415]: ./postinstall:        cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
Jan 16 11:52:17 mac installd[415]: ./postinstall: chown: /Users/redacted/Library/Application: No such file or directory
Jan 16 11:52:17 mac installd[415]: ./postinstall: chown: Support/zxpinstaller: No such file or directory
Jan 16 11:52:17 mac installd[415]: PackageKit: Writing receipt for co.misusu.ai18n to /
Jan 16 11:52:17 mac installd[415]: Installed "Misusu ai18n" ()
Jan 16 11:52:17 mac install_monitor[51496]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
...
```
It's probably unrelated, but it looks like the escaping/quoting of the space in the `/LibraryApplication Support/zxpinstaller` is done incorrectly.

I ended up manually extracting the bundle.zxp into `/Library/Application Support/Adobe/CEP/extensions/BUNDLE_ID` and things are working fine.

I'm not sure why `ExManCmd` returns -403 while the app is installed...

[here]: https://partners.adobe.com/exchangeprogram/creativecloud/support/exman-com-line-tool.html

**Comment by vespakoen** [comment]
Thanks for the detailed report, there seems to be an escaping issue indeed! I'll fix that.
That command runs after ExManCmd tries to install the package though, and is not crucial for a successful install.
The postinstall script also tries to remove the package before installing it, so you can install the same version again without ExManCmd complaining (handy for when you have built an installer with the same version number as the last one) this command is allowed to fail though:

```
./ExManCmd_mac/Contents/MacOS/ExManCmd --remove ${opts.bundleId} || true >> $HOME/.installer-debug-log.txt 2>&1
```

Notice `|| true`

Can you paste the full contents of your manifest.xml file?

You can also add me on hangouts if you'd like me to take a look: hello@koenschmeets.nl ;)

**Comment by vespakoen** [comment]
Just tried over here:

```
cd Projects/adobe-extension-tools/cep-starter
npm install
npm run package
open dist/1.0.0.pkg
cat ~/.installer-debug-log.txt
```

```
Running installer...
Installing extension with file path = ./bundle.zxp
Installation Successful for extension with file path = ./bundle.zxp
Done.
```

**Comment by martijnthe** [comment]
Here's the full manifest.xml.
I'll ping you on hangouts so we can debug.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ExtensionManifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ExtensionBundleId="co.misusu.ai18n" ExtensionBundleName="Misusu ai18n" ExtensionBundleVersion="1.0.0" Version="6.0">
  <ExtensionList>
    <Extension Id="co.misusu.ai18n" Version="1.0.0"/>
  </ExtensionList>
  <ExecutionEnvironment>
    <HostList>
      <Host Name="PHXS" Version="[1.0,99.9]" />
      <Host Name="PHSP" Version="[1.0,99.9]" />
      <Host Name="IDSN" Version="[1.0,99.9]" />
      <Host Name="AICY" Version="[1.0,99.9]" />
      <Host Name="ILST" Version="[1.0,99.9]" />
      <Host Name="PPRO" Version="[1.0,99.9]" />
      <Host Name="PRLD" Version="[1.0,99.9]" />
      <Host Name="AEFT" Version="[1.0,99.9]" />
      <Host Name="FLPR" Version="[1.0,99.9]" />
      <Host Name="AUDT" Version="[1.0,99.9]" />
      <Host Name="DRWV" Version="[1.0,99.9]" />
      <Host Name="MUSE" Version="[1.0,99.9]" />
      <Host Name="KBRG" Version="[1.0,99.9]" />
    </HostList>
    <LocaleList>
      <Locale Code="All"/>
    </LocaleList>
    <RequiredRuntimeList>
      <RequiredRuntime Name="CSXS" Version="6.0"/>
    </RequiredRuntimeList>
  </ExecutionEnvironment>
  <DispatchInfoList>
    <Extension Id="co.misusu.ai18n">
      <DispatchInfo>
        <Resources>
          <MainPath>./index.html</MainPath>
          <CEFCommandLine>
            <Parameter>--allow-file-access-from-files</Parameter>
      <Parameter>--allow-file-access</Parameter>
      <Parameter>--enable-nodejs</Parameter>
      <Parameter>--mixed-context</Parameter>
          </CEFCommandLine>
        </Resources>
        <Lifecycle>
          <AutoVisible>true</AutoVisible>
        </Lifecycle>
        <UI>
          <Type>Panel</Type>
          <Menu>Misusu ai18n</Menu>
          <Geometry>
            <Size>
              <Height>200</Height>
              <Width>200</Width>
            </Size>
            <MaxSize>
              <Height>10000</Height>
              <Width>10000</Width>
            </MaxSize>
            <MinSize>
              <Height>200</Height>
              <Width>200</Width>
            </MinSize>
          </Geometry>
        </UI>
      </DispatchInfo>
    </Extension>
  </DispatchInfoList>
</ExtensionManifest>
```

**Comment by martijnthe** [comment]
After poking around for a bit (manually invoking the most recent version of`ExManCmd`), `ExManCmd` finally decided to install the package without error (even with the .pkg installer that was failing at first...)

¯\\__(ツ)_/¯

**Comment by timolins** [comment]
I am experiencing the same issue at the moment. Also tried to install the .zxp file with `ExManCmd` but it throws me the same -403 error. Anything else that I could try?

**Comment by vespakoen** [comment]
Please checkout the latest code on the #catalina branch, it gets rid of ExManCmd completely.

**Comment by timolins** [comment]
Awesome, now it works just fine! The size of the installer also went down drastically, which is a welcome change.
